{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "localstack.roleBindingName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: {{ include "localstack.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "localstack.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
