{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "localstack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
  annotations:
    {{- include "localstack.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
