apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: {{ .Values.service.edgeService.name }}
      port: {{ .Values.service.edgeService.targetPort }}
      targetPort: {{ .Values.service.edgeService.targetPort }}
      {{- if and (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) (not (empty .Values.service.edgeService.nodePort)) }}
      nodePort: {{ .Values.service.edgeService.nodePort }}
      {{- end }}
    {{- range .Values.service.apiServices }}
    - name: {{ .name }}
      port: {{ .targetPort }}
      targetPort: {{ .targetPort }}
      {{- if and (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
