apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
  annotations:
    {{- include "localstack.annotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- with .Values.service.ipFamilies }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: {{ .Values.service.edgeService.name }}
      port: {{ .Values.service.edgeService.targetPort }}
      targetPort: {{ .Values.service.edgeService.targetPort }}
      {{- if and (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) (not (empty .Values.service.edgeService.nodePort)) }}
      nodePort: {{ .Values.service.edgeService.nodePort }}
      {{- end }}
    {{- if .Values.service.dnsService }}
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    {{- end }}
    {{- range $index, $port := untilStep (.Values.service.externalServicePorts.start|int) (.Values.service.externalServicePorts.end|int) 1 }}
    - name: "external-service-port-{{ $port }}"
      port: {{ $port }}
      targetPort: "ext-svc-{{ $port }}"
    {{- with $.Values.service.externalServicePorts.nodePortStart|int }}
      nodePort: {{ add $index . }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
