apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: edgeport
      port: {{ .Values.service.edgePort }}
      targetPort: {{ .Values.service.edgePort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.nodePorts.edgePort)) }}
      nodePort: {{ .Values.nodePorts.edgePort }}
      {{- end }}
    - name: esport
      port: {{ .Values.service.esPort }}
      targetPort: {{ .Values.service.esPort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.nodePorts.esPort)) }}
      nodePort: {{ .Values.nodePorts.esPort }}
      {{- end }}
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
