annotations:
  category: Infrastructure
apiVersion: v2
appVersion: "latest"
version: 0.1.1
name: localstack
description: A fully functional local AWS cloud stack
type: application
keywords:
  - aws
  - localstack
sources:
- https://localstack.cloud/
- https://github.com/localstack/localstack
icon: https://github.com/localstack/localstack/raw/master/localstack/dashboard/web/img/localstack.png
maintainers:
- name: Waldemar Hummer
  email: waldemar.hummer@gmail.com